/*
 * NVIC_Types.h
 *
 *  Created on: 2023. okt. 19.
 *      Author: Benjamin
 */

#ifndef INC_MEMMAP_TYPES_NVIC_TYPES_H_
#define INC_MEMMAP_TYPES_NVIC_TYPES_H_

/* NVIC typedef definitions */

typedef struct
{
    uint32 ISER[8];
} dtISER;

typedef struct
{
    uint32 ICER[8];
} dtICER;

typedef struct
{
    uint32 ISPR[8];
} dtISPR;

typedef struct
{
    uint32 ICPR[8];
} dtICPR;

typedef struct
{
    uint32 IABR[8];
} dtIABR;

typedef struct
{
    uint8 PRI[240];
} dtIPR;

typedef union
{
    uint32 Word;
    struct
    {
        uint32          :31;
        uint32 PRIMASK  :1;
    } Fields;
} dtPRIMASK;


/* Core type definitions */

#define CORE_ICSR_NMIPENDSET_WIDTH  1
#define CORE_ICSR_PENDSVSET_WIDTH   1
#define CORE_ICSR_PENDSVCLR_WIDTH   1
#define CORE_ICSR_PENDSTSET_WIDTH   1
#define CORE_ICSR_PENDSTCLR_WIDTH   1
#define CORE_ICSR_ISRPREEMPT_WIDTH  1
#define CORE_ICSR_ISRPENDING_WIDTH  1
#define CORE_ICSR_VECTPENDING_WIDTH 9
#define CORE_ICSR_RETTOBASE_WIDTH   1
#define CORE_ICSR_VECTACTIVE_WIDTH  9

#define CORE_ICSR_NMIPENDSET_PLACE  31
#define CORE_ICSR_PENDSVSET_PLACE   28
#define CORE_ICSR_PENDSVCLR_PLACE   27
#define CORE_ICSR_PENDSTSET_PLACE   26
#define CORE_ICSR_PENDSTCLR_PLACE   25
#define CORE_ICSR_ISRPREEMPT_PLACE  23
#define CORE_ICSR_ISRPENDING_PLACE  22
#define CORE_ICSR_VECTPENDING_PLACE 12
#define CORE_ICSR_RETTOBASE_PLACE   11
#define CORE_ICSR_VECTACTIVE_PLACE  0

#define CORE_ICSR_NMIPENDSET_MASK  (1)<<CORE_ICSR_NMIPENDSET_PLACE
#define CORE_ICSR_PENDSVSET_MASK   (1)<<CORE_ICSR_PENDSVSET_PLACE
#define CORE_ICSR_PENDSVCLR_MASK   (1)<<CORE_ICSR_PENDSVCLR_PLACE
#define CORE_ICSR_PENDSTSET_MASK   (1)<<CORE_ICSR_PENDSTSET_PLACE
#define CORE_ICSR_PENDSTCLR_MASK   (1)<<CORE_ICSR_PENDSTCLR_PLACE
#define CORE_ICSR_ISRPREEMPT_MASK  (1)<<CORE_ICSR_ISRPREEMPT_PLACE
#define CORE_ICSR_ISRPENDING_MASK  (1)<<CORE_ICSR_ISRPENDING_PLACE
#define CORE_ICSR_VECTPENDING_MASK (0x1FF)<<CORE_ICSR_VECTPENDING_PLACE
#define CORE_ICSR_RETTOBASE_MASK   (1)<<CORE_ICSR_RETTOBASE_PLACE
#define CORE_ICSR_VECTACTIVE_MASK  (0x1FF)<<CORE_ICSR_VECTACTIVE_PLACE

#endif /* INC_MEMMAP_TYPES_NVIC_TYPES_H_ */
