/*
 * RCC_Test_L433.c
 *
 *  Created on: 2020. okt. 13.
 *      Author: BodnarB
 */

#define TEST_CASE
#include "TestEnv.h"

void RCC_Test(void);
void RCC_TestCase_1(void);

void RCC_Test(void)
{
	RCC_TestCase_1();
}

/*
 * This test case tests the various enabling and disabling of the peripherals
 */
void RCC_TestCase_1(void)
{
	/********************************/
	/* Test of enabling peripherals */
	/********************************/
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA1, 0);
	RCC_ClockEnable(RCC_DMA1, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA1, 1);

	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA2, 0);
	RCC_ClockEnable(RCC_DMA2, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA2, 1);

	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.FLASH, 0);
	RCC_ClockEnable(RCC_FLASH, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.FLASH, 1);

	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.CRC, 0);
	RCC_ClockEnable(RCC_CRC, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.CRC, 1);

	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.TSC, 0);
	RCC_ClockEnable(RCC_TSC, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.TSC, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOA, 0);
	RCC_ClockEnable(RCC_GPIOA, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOA, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOB, 0);
	RCC_ClockEnable(RCC_GPIOB, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOB, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOC, 0);
	RCC_ClockEnable(RCC_GPIOC, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOC, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOD, 0);
	RCC_ClockEnable(RCC_GPIOD, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOD, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOE, 0);
	RCC_ClockEnable(RCC_GPIOE, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOE, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOH, 0);
	RCC_ClockEnable(RCC_GPIOH, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOH, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.ADC, 0);
	RCC_ClockEnable(RCC_ADC, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.ADC, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.AES, 0);
	RCC_ClockEnable(RCC_AES, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.AES, 1);

	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.RNG, 0);
	RCC_ClockEnable(RCC_RNG, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.RNG, 1);

	ASSERT_EQ(TestRCC.ENR.AHB3.Fields.QSPI, 0);
	RCC_ClockEnable(RCC_QSPI, Enable);
	ASSERT_EQ(TestRCC.ENR.AHB3.Fields.QSPI, 1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM2,0);
	RCC_ClockEnable(RCC_TIM2, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM2,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM3,0);
	RCC_ClockEnable(RCC_TIM3, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM3,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM6,0);
	RCC_ClockEnable(RCC_TIM6, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM6,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM7,0);
	RCC_ClockEnable(RCC_TIM7, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM7,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LCD,0);
	RCC_ClockEnable(RCC_LCD, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LCD,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI2,0);
	RCC_ClockEnable(RCC_SPI2, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI2,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI3,0);
	RCC_ClockEnable(RCC_SPI3, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI3,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART2,0);
	RCC_ClockEnable(RCC_USART2, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART2,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART3,0);
	RCC_ClockEnable(RCC_USART3, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART3,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART4,0);
	RCC_ClockEnable(RCC_USART4, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART4,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C1,0);
	RCC_ClockEnable(RCC_I2C1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C1,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C2,0);
	RCC_ClockEnable(RCC_I2C2, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C2,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C3,0);
	RCC_ClockEnable(RCC_I2C3, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C3,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CRS,0);
	RCC_ClockEnable(RCC_CRS, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CRS,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CAN1,0);
	RCC_ClockEnable(RCC_CAN1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CAN1,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USBFS,0);
	RCC_ClockEnable(RCC_USB_FS, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USBFS,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.PWR,0);
	RCC_ClockEnable(RCC_PWR, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.PWR,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.DAC1,0);
	RCC_ClockEnable(RCC_DAC, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.DAC1,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.OPAMP,0);
	RCC_ClockEnable(RCC_OPAMP, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.OPAMP,1);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LPTIM1,0);
	RCC_ClockEnable(RCC_LPTIM1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LPTIM1,1);

	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPUART1,0);
	RCC_ClockEnable(RCC_LPUART1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPUART1,1);

	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.I2C4,0);
	RCC_ClockEnable(RCC_I2C4, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.I2C4,1);

	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.SWPMI1,0);
	RCC_ClockEnable(RCC_SWPMI1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.SWPMI1,1);

	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPTIM2,0);
	RCC_ClockEnable(RCC_LPTIM2, Enable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPTIM2,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SYSCFG,0);
	RCC_ClockEnable(RCC_SYSCFG, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SYSCFG,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SDMMC1,0);
	RCC_ClockEnable(RCC_SDMMC1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SDMMC1,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM1,0);
	RCC_ClockEnable(RCC_TIM1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM1,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SPI1,0);
	RCC_ClockEnable(RCC_SPI1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SPI1,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.USART1,0);
	RCC_ClockEnable(RCC_USART1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.USART1,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM15,0);
	RCC_ClockEnable(RCC_TIM15, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM15,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM16,0);
	RCC_ClockEnable(RCC_TIM16, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM16,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SAI1,0);
	RCC_ClockEnable(RCC_SAI1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SAI1,1);

	ASSERT_EQ(TestRCC.ENR.APB2.Fields.DFSDM1,0);
	RCC_ClockEnable(RCC_DFSDM1, Enable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.DFSDM1,1);

	/************************************/
	/* Test of disabling of peripherals */
	/************************************/

	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA1, 1);
	RCC_ClockEnable(RCC_DMA1, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA1, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA2, 1);
	RCC_ClockEnable(RCC_DMA2, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.DMA2, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.FLASH, 1);
	RCC_ClockEnable(RCC_FLASH, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.FLASH, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.CRC, 1);
	RCC_ClockEnable(RCC_CRC, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.CRC, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.TSC, 1);
	RCC_ClockEnable(RCC_TSC, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB1.Fields.TSC, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOA, 1);
	RCC_ClockEnable(RCC_GPIOA, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOA, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOB, 1);
	RCC_ClockEnable(RCC_GPIOB, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOB, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOC, 1);
	RCC_ClockEnable(RCC_GPIOC, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOC, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOD, 1);
	RCC_ClockEnable(RCC_GPIOD, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOD, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOE, 1);
	RCC_ClockEnable(RCC_GPIOE, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOE, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOH, 1);
	RCC_ClockEnable(RCC_GPIOH, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.GPIOH, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.ADC, 1);
	RCC_ClockEnable(RCC_ADC, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.ADC, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.AES, 1);
	RCC_ClockEnable(RCC_AES, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.AES, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.RNG, 1);
	RCC_ClockEnable(RCC_RNG, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB2.Fields.RNG, 0);
	
	ASSERT_EQ(TestRCC.ENR.AHB3.Fields.QSPI, 1);
	RCC_ClockEnable(RCC_QSPI, Disable);
	ASSERT_EQ(TestRCC.ENR.AHB3.Fields.QSPI, 0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM2,1);
	RCC_ClockEnable(RCC_TIM2, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM2,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM3,1);
	RCC_ClockEnable(RCC_TIM3, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM3,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM6,1);
	RCC_ClockEnable(RCC_TIM6, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM6,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM7,1);
	RCC_ClockEnable(RCC_TIM7, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.TIM7,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LCD,1);
	RCC_ClockEnable(RCC_LCD, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LCD,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI2,1);
	RCC_ClockEnable(RCC_SPI2, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI2,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI3,1);
	RCC_ClockEnable(RCC_SPI3, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.SPI3,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART2,1);
	RCC_ClockEnable(RCC_USART2, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART2,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART3,1);
	RCC_ClockEnable(RCC_USART3, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART3,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART4,1);
	RCC_ClockEnable(RCC_USART4, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USART4,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C1,1);
	RCC_ClockEnable(RCC_I2C1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C2,1);
	RCC_ClockEnable(RCC_I2C2, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C2,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C3,1);
	RCC_ClockEnable(RCC_I2C3, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.I2C3,0);

	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CRS,1);
	RCC_ClockEnable(RCC_CRS, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CRS,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CAN1,1);
	RCC_ClockEnable(RCC_CAN1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.CAN1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USBFS,1);
	RCC_ClockEnable(RCC_USB_FS, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.USBFS,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.PWR,1);
	RCC_ClockEnable(RCC_PWR, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.PWR,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.DAC1,1);
	RCC_ClockEnable(RCC_DAC, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.DAC1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.OPAMP,1);
	RCC_ClockEnable(RCC_OPAMP, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.OPAMP,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LPTIM1,1);
	RCC_ClockEnable(RCC_LPTIM1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1.Fields.LPTIM1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPUART1,1);
	RCC_ClockEnable(RCC_LPUART1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPUART1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.I2C4,1);
	RCC_ClockEnable(RCC_I2C4, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.I2C4,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.SWPMI1,1);
	RCC_ClockEnable(RCC_SWPMI1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.SWPMI1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPTIM2,1);
	RCC_ClockEnable(RCC_LPTIM2, Disable);
	ASSERT_EQ(TestRCC.ENR.APB1_2.Fields.LPTIM2,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SYSCFG,1);
	RCC_ClockEnable(RCC_SYSCFG, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SYSCFG,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SDMMC1,1);
	RCC_ClockEnable(RCC_SDMMC1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SDMMC1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM1,1);
	RCC_ClockEnable(RCC_TIM1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SPI1,1);
	RCC_ClockEnable(RCC_SPI1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SPI1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.USART1,1);
	RCC_ClockEnable(RCC_USART1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.USART1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM15,1);
	RCC_ClockEnable(RCC_TIM15, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM15,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM16,1);
	RCC_ClockEnable(RCC_TIM16, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.TIM16,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SAI1,1);
	RCC_ClockEnable(RCC_SAI1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.SAI1,0);
	
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.DFSDM1,1);
	RCC_ClockEnable(RCC_DFSDM1, Disable);
	ASSERT_EQ(TestRCC.ENR.APB2.Fields.DFSDM1,0);

    /***********************/
	/* Test of LP enabling */
    /***********************/

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA1, 0);
	RCC_ClockEnable(RCC_DMA1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA1, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA2, 0);
	RCC_ClockEnable(RCC_DMA2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA2, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.FLASH, 0);
	RCC_ClockEnable(RCC_FLASH, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.FLASH, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.CRC, 0);
	RCC_ClockEnable(RCC_CRC, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.CRC, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.TSC, 0);
	RCC_ClockEnable(RCC_TSC, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.TSC, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOA, 0);
	RCC_ClockEnable(RCC_GPIOA, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOA, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOB, 0);
	RCC_ClockEnable(RCC_GPIOB, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOB, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOC, 0);
	RCC_ClockEnable(RCC_GPIOC, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOC, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOD, 0);
	RCC_ClockEnable(RCC_GPIOD, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOD, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOE, 0);
	RCC_ClockEnable(RCC_GPIOE, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOE, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOH, 0);
	RCC_ClockEnable(RCC_GPIOH, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOH, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.ADC, 0);
	RCC_ClockEnable(RCC_ADC, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.ADC, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.AES, 0);
	RCC_ClockEnable(RCC_AES, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.AES, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.RNG, 0);
	RCC_ClockEnable(RCC_RNG, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.RNG, 1);

	ASSERT_EQ(TestRCC.SMENR.AHB3.Fields.QSPI, 0);
	RCC_ClockEnable(RCC_QSPI, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.AHB3.Fields.QSPI, 1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM2,0);
	RCC_ClockEnable(RCC_TIM2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM2,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM3,0);
	RCC_ClockEnable(RCC_TIM3, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM3,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM6,0);
	RCC_ClockEnable(RCC_TIM6, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM6,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM7,0);
	RCC_ClockEnable(RCC_TIM7, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM7,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LCD,0);
	RCC_ClockEnable(RCC_LCD, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LCD,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI2,0);
	RCC_ClockEnable(RCC_SPI2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI2,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI3,0);
	RCC_ClockEnable(RCC_SPI3, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI3,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART2,0);
	RCC_ClockEnable(RCC_USART2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART2,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART3,0);
	RCC_ClockEnable(RCC_USART3, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART3,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART4,0);
	RCC_ClockEnable(RCC_USART4, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART4,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C1,0);
	RCC_ClockEnable(RCC_I2C1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C2,0);
	RCC_ClockEnable(RCC_I2C2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C2,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C3,0);
	RCC_ClockEnable(RCC_I2C3, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C3,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CRS,0);
	RCC_ClockEnable(RCC_CRS, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CRS,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CAN1,0);
	RCC_ClockEnable(RCC_CAN1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CAN1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USBFS,0);
	RCC_ClockEnable(RCC_USB_FS, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USBFS,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.PWR,0);
	RCC_ClockEnable(RCC_PWR, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.PWR,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.DAC1,0);
	RCC_ClockEnable(RCC_DAC, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.DAC1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.OPAMP,0);
	RCC_ClockEnable(RCC_OPAMP, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.OPAMP,1);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LPTIM1,0);
	RCC_ClockEnable(RCC_LPTIM1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LPTIM1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPUART1,0);
	RCC_ClockEnable(RCC_LPUART1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPUART1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.I2C4,0);
	RCC_ClockEnable(RCC_I2C4, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.I2C4,1);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.SWPMI1,0);
	RCC_ClockEnable(RCC_SWPMI1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.SWPMI1,1);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPTIM2,0);
	RCC_ClockEnable(RCC_LPTIM2, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPTIM2,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SYSCFG,0);
	RCC_ClockEnable(RCC_SYSCFG, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SYSCFG,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SDMMC1,0);
	RCC_ClockEnable(RCC_SDMMC1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SDMMC1,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM1,0);
	RCC_ClockEnable(RCC_TIM1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM1,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SPI1,0);
	RCC_ClockEnable(RCC_SPI1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SPI1,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.USART1,0);
	RCC_ClockEnable(RCC_USART1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.USART1,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM15,0);
	RCC_ClockEnable(RCC_TIM15, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM15,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM16,0);
	RCC_ClockEnable(RCC_TIM16, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM16,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SAI1,0);
	RCC_ClockEnable(RCC_SAI1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SAI1,1);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.DFSDM1,0);
	RCC_ClockEnable(RCC_DFSDM1, LpEnable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.DFSDM1,1);

	/***********************/
	/* Test of LP disabling */
	/***********************/

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA1, 1);
	RCC_ClockEnable(RCC_DMA1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA1, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA2, 1);
	RCC_ClockEnable(RCC_DMA2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.DMA2, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.FLASH, 1);
	RCC_ClockEnable(RCC_FLASH,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.FLASH, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.CRC, 1);
	RCC_ClockEnable(RCC_CRC,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.CRC, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.TSC, 1);
	RCC_ClockEnable(RCC_TSC,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB1.Fields.TSC, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOA, 1);
	RCC_ClockEnable(RCC_GPIOA,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOA, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOB, 1);
	RCC_ClockEnable(RCC_GPIOB,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOB, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOC, 1);
	RCC_ClockEnable(RCC_GPIOC,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOC, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOD, 1);
	RCC_ClockEnable(RCC_GPIOD,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOD, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOE, 1);
	RCC_ClockEnable(RCC_GPIOE,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOE, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOH, 1);
	RCC_ClockEnable(RCC_GPIOH,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.GPIOH, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.ADC, 1);
	RCC_ClockEnable(RCC_ADC,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.ADC, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.AES, 1);
	RCC_ClockEnable(RCC_AES,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.AES, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.RNG, 1);
	RCC_ClockEnable(RCC_RNG,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB2.Fields.RNG, 0);

	ASSERT_EQ(TestRCC.SMENR.AHB3.Fields.QSPI, 1);
	RCC_ClockEnable(RCC_QSPI,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.AHB3.Fields.QSPI, 0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM2,1);
	RCC_ClockEnable(RCC_TIM2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM2,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM3,1);
	RCC_ClockEnable(RCC_TIM3,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM3,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM6,1);
	RCC_ClockEnable(RCC_TIM6,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM6,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM7,1);
	RCC_ClockEnable(RCC_TIM7,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.TIM7,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LCD,1);
	RCC_ClockEnable(RCC_LCD,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LCD,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI2,1);
	RCC_ClockEnable(RCC_SPI2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI2,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI3,1);
	RCC_ClockEnable(RCC_SPI3,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.SPI3,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART2,1);
	RCC_ClockEnable(RCC_USART2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART2,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART3,1);
	RCC_ClockEnable(RCC_USART3,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART3,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART4,1);
	RCC_ClockEnable(RCC_USART4,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USART4,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C1,1);
	RCC_ClockEnable(RCC_I2C1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C2,1);
	RCC_ClockEnable(RCC_I2C2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C2,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C3,1);
	RCC_ClockEnable(RCC_I2C3,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.I2C3,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CRS,1);
	RCC_ClockEnable(RCC_CRS,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CRS,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CAN1,1);
	RCC_ClockEnable(RCC_CAN1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.CAN1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USBFS,1);
	RCC_ClockEnable(RCC_USB_FS,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.USBFS,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.PWR,1);
	RCC_ClockEnable(RCC_PWR,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.PWR,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.DAC1,1);
	RCC_ClockEnable(RCC_DAC,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.DAC1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.OPAMP,1);
	RCC_ClockEnable(RCC_OPAMP,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.OPAMP,0);

	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LPTIM1,1);
	RCC_ClockEnable(RCC_LPTIM1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1.Fields.LPTIM1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPUART1,1);
	RCC_ClockEnable(RCC_LPUART1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPUART1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.I2C4,1);
	RCC_ClockEnable(RCC_I2C4,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.I2C4,0);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.SWPMI1,1);
	RCC_ClockEnable(RCC_SWPMI1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.SWPMI1,0);

	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPTIM2,1);
	RCC_ClockEnable(RCC_LPTIM2,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB1_2.Fields.LPTIM2,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SYSCFG,1);
	RCC_ClockEnable(RCC_SYSCFG,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SYSCFG,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SDMMC1,1);
	RCC_ClockEnable(RCC_SDMMC1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SDMMC1,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM1,1);
	RCC_ClockEnable(RCC_TIM1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM1,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SPI1,1);
	RCC_ClockEnable(RCC_SPI1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SPI1,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.USART1,1);
	RCC_ClockEnable(RCC_USART1,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.USART1,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM15,1);
	RCC_ClockEnable(RCC_TIM15,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM15,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM16,1);
	RCC_ClockEnable(RCC_TIM16,LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.TIM16,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SAI1,1);
	RCC_ClockEnable(RCC_SAI1, LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.SAI1,0);

	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.DFSDM1,1);
	RCC_ClockEnable(RCC_DFSDM1, LpDisable);
	ASSERT_EQ(TestRCC.SMENR.APB2.Fields.DFSDM1,0);

	/********************************/
	/* Test of reseting peripherals */
    /********************************/

	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.DMA1, 0);
	RCC_ClockEnable(RCC_DMA1, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.DMA1, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.DMA2, 0);
	RCC_ClockEnable(RCC_DMA2, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.DMA2, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.FLASH, 0);
	RCC_ClockEnable(RCC_FLASH, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.FLASH, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.CRC, 0);
	RCC_ClockEnable(RCC_CRC, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.CRC, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.TSC, 0);
	RCC_ClockEnable(RCC_TSC, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB1.Fields.TSC, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOA, 0);
	RCC_ClockEnable(RCC_GPIOA, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOA, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOB, 0);
	RCC_ClockEnable(RCC_GPIOB, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOB, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOC, 0);
	RCC_ClockEnable(RCC_GPIOC, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOC, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOD, 0);
	RCC_ClockEnable(RCC_GPIOD, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOD, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOE, 0);
	RCC_ClockEnable(RCC_GPIOE, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOE, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOH, 0);
	RCC_ClockEnable(RCC_GPIOH, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.GPIOH, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.ADC, 0);
	RCC_ClockEnable(RCC_ADC, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.ADC, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.AES, 0);
	RCC_ClockEnable(RCC_AES, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.AES, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.RNG, 0);
	RCC_ClockEnable(RCC_RNG, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB2.Fields.RNG, 1);

	ASSERT_EQ(TestRCC.RSTR.AHB3.Fields.QSPI, 0);
	RCC_ClockEnable(RCC_QSPI, Reset);
	ASSERT_EQ(TestRCC.RSTR.AHB3.Fields.QSPI, 1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM2,0);
	RCC_ClockEnable(RCC_TIM2, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM2,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM3,0);
	RCC_ClockEnable(RCC_TIM3, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM3,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM6,0);
	RCC_ClockEnable(RCC_TIM6, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM6,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM7,0);
	RCC_ClockEnable(RCC_TIM7, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.TIM7,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.LCD,0);
	RCC_ClockEnable(RCC_LCD, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.LCD,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.SPI2,0);
	RCC_ClockEnable(RCC_SPI2, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.SPI2,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.SPI3,0);
	RCC_ClockEnable(RCC_SPI3, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.SPI3,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART2,0);
	RCC_ClockEnable(RCC_USART2, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART2,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART3,0);
	RCC_ClockEnable(RCC_USART3, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART3,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART4,0);
	RCC_ClockEnable(RCC_USART4, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USART4,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C1,0);
	RCC_ClockEnable(RCC_I2C1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C2,0);
	RCC_ClockEnable(RCC_I2C2, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C2,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C3,0);
	RCC_ClockEnable(RCC_I2C3, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.I2C3,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.CRS,0);
	RCC_ClockEnable(RCC_CRS, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.CRS,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.CAN1,0);
	RCC_ClockEnable(RCC_CAN1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.CAN1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USBFS,0);
	RCC_ClockEnable(RCC_USB_FS, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.USBFS,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.PWR,0);
	RCC_ClockEnable(RCC_PWR, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.PWR,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.DAC1,0);
	RCC_ClockEnable(RCC_DAC, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.DAC1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.OPAMP,0);
	RCC_ClockEnable(RCC_OPAMP, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.OPAMP,1);

	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.LPTIM1,0);
	RCC_ClockEnable(RCC_LPTIM1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1.Fields.LPTIM1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.LPUART1,0);
	RCC_ClockEnable(RCC_LPUART1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.LPUART1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.I2C4,0);
	RCC_ClockEnable(RCC_I2C4, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.I2C4,1);

	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.SWPMI1,0);
	RCC_ClockEnable(RCC_SWPMI1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.SWPMI1,1);

	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.LPTIM2,0);
	RCC_ClockEnable(RCC_LPTIM2, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB1_2.Fields.LPTIM2,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SYSCFG,0);
	RCC_ClockEnable(RCC_SYSCFG, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SYSCFG,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SDMMC1,0);
	RCC_ClockEnable(RCC_SDMMC1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SDMMC1,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM1,0);
	RCC_ClockEnable(RCC_TIM1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM1,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SPI1,0);
	RCC_ClockEnable(RCC_SPI1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SPI1,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.USART1,0);
	RCC_ClockEnable(RCC_USART1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.USART1,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM15,0);
	RCC_ClockEnable(RCC_TIM15, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM15,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM16,0);
	RCC_ClockEnable(RCC_TIM16, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.TIM16,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SAI1,0);
	RCC_ClockEnable(RCC_SAI1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.SAI1,1);

	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.DFSDM1,0);
	RCC_ClockEnable(RCC_DFSDM1, Reset);
	ASSERT_EQ(TestRCC.RSTR.APB2.Fields.DFSDM1,1);
}

